Optimized Max Calls Per Time Unit computation for zero values
skalenetwork/skaled pull request #1288
Opened 2022-12-21 20:58 UTC by sergiy-skalelabs

Optimized Max Calls Per Time Unit computation for zero values

2022-12-23 10:22 UTC, DmytroNazarenko requested changes

2022-12-23 10:22 UTC, DmytroNazarenko commented on libskutils/include/skutils/unddos.h
> +#define __UNDDOS_SUPPORT_4_GLOBAL_SUMMARY__ 1
Remove please unnecessary __UNDDOS_SUPPORT_4_GLOBAL_SUMMARY__

2022-12-23 18:25 UTC, sergiy-skalelabs commented on libskutils/include/skutils/unddos.h
> +#define __UNDDOS_SUPPORT_4_GLOBAL_SUMMARY__ 1
done

2022-12-28 19:54 UTC, DmytroNazarenko approved these changes

2022-12-29 11:59 UTC, dimalit approved these changes

2022-12-29 12:05 UTC, merged