Feature/skale 1837 add bls signatures to snapshots
skalenetwork/skaled pull request #147
Opened 2019-12-20 12:35 UTC by olehnikolaiev

medium risk
add signing snapshots with BLS signatures

2019-12-20 17:05 UTC, kladkogex submitted a review, later dismissed

2019-12-23 16:33 UTC, dimalit requested changes
1) Read config at program start - and not in JSON-RPC calls
2) Add methods to SkaleClient and use them

2020-01-03 16:44 UTC, sergiy-skalelabs approved these changes

2020-01-03 17:40 UTC, dimalit approved these changes

2020-01-03 17:40 UTC, merged