Feature/1506 run rpc without 2/3 nodes
skalenetwork/skaled pull request #1540
Opened 2023-06-08 10:26 UTC by olehnikolaiev

2023-06-16 20:07 UTC, kladkogex commented
Lets discuss on Monday )

2023-06-18 22:59 UTC, kladkogex commented
I added logic to consensus so it is does not wait for EMPTY_BLOCK_TIMEOUT during bootstrap all

2023-06-18 23:37 UTC, kladkogex requested changes
I moved the logic to setEmptyBlockInterval to 50 ms initially to consensus, 
it is cleaner this way.

Please modify the pull request)

I think it may be not needed anymore

2023-06-19 18:57 UTC, DmytroNazarenko approved these changes

2023-06-19 19:54 UTC, sergiy-skalelabs approved these changes

2023-06-19 23:49 UTC, kladkogex approved these changes

2023-06-20 06:26 UTC, merged