Version 1.40 to beta
skalenetwork/skaled pull request #167
Opened 2020-01-17 17:42 UTC by dimalit

2020-01-17 22:13 UTC, sergiy-skalelabs approved these changes

2020-01-18 11:26 UTC, sergiy-skalelabs approved these changes

2020-01-22 12:33 UTC, DimaStebaev approved these changes

2020-01-22 12:38 UTC, DimaStebaev requested changes
Merge beta to stable first.

2020-01-23 10:20 UTC, DimaStebaev approved these changes

2020-01-23 10:21 UTC, merged