Bug/skaled 1623 sigterm at exit
skalenetwork/skaled pull request #1695
Opened 2023-10-17 18:49 UTC by dimalit

Tested manually by emulating internal exit and sending SIGTERM

2023-10-17 18:52 UTC, dimalit commented
Probably, let's wait for "stable" - it will integrate changes in develop into v3.18.0 - and this PR would not be so bloated

2023-11-14 20:29 UTC, kladkogex requested changes

2023-11-14 20:29 UTC, kladkogex commented on libdevcore/Common.cpp
> +                               cc::error( "\nStop flag was already raised on. " ) +
Please remove color comments

2023-11-14 20:29 UTC, kladkogex commented on libdevcore/Common.cpp
>      std::cerr.flush();
Remove this line since cerr is always flushed on line end

2023-11-14 20:29 UTC, kladkogex commented on libdevcore/Common.cpp
>          _exit( 13 );
Why is 13 used here ? Is there a document in which error codes are defined?

2023-11-15 17:57 UTC, DmytroNazarenko approved these changes, later dismissed
Approved, next steps:
1. Need to add test to functional-tests
2. Fix colorization
4. Test build on devnet

2023-11-20 16:46 UTC, dimalit commented
UPD Currently, functional tests fail in load_js. But fail happens because of skaled JSON-RPC request refusal. As changes in this PR cannot affect JSON-RPC at all - most probably, issue is because of Debug build instead of Release build. It should be gone after merge and Release build.

2023-11-21 12:35 UTC, DmytroNazarenko approved these changes

2023-11-21 13:15 UTC, merged