Bug/1702 adopt precompiled oracle
skalenetwork/skaled pull request #1713
Opened 2023-10-31 12:19 UTC by olehnikolaiev

fixes #1702

2023-11-03 12:10 UTC, kladkogex requested changes
Please use a patch mechanism to switch the code changes on at a particular block id

Also please provided a detailed explaination in pull request description how the pull request was tested

2023-11-03 13:39 UTC, kladkogex requested changes
please either add detailed comments how the fix was made (preferred)
Or describe details of the fix in pull request

2023-11-08 15:43 UTC, kladkogex submitted a review, later dismissed

2023-11-08 15:43 UTC, kladkogex commented on libethereum/Precompiled.cpp
> +    // skaled-1702
Please remove the commented out section

According to the code guidelines we do not keep dead code

2023-11-08 15:43 UTC, kladkogex commented on libethereum/Precompiled.cpp
>      //"genesis.*"
Please remove sealEngine parameter, since it is never used, and is always equal to ethHash

2023-11-08 15:43 UTC, kladkogex commented on libethereum/Precompiled.cpp
>      //"genesis.*"
Please change stat_is_accessible_json_path fuction to use boost starts_with

2023-11-08 15:43 UTC, kladkogex commented on libethereum/Precompiled.cpp
> +static std::pair< std::string, unsigned > parseHistoricFieldReuqest( const std::string& callData ) {
Please improve so that exact matches are always used, so inccorect strings do not result in a match

2023-11-08 15:43 UTC, kladkogex commented on libethereum/Precompiled.cpp
> +        }
Please change so that the else {} part is only used when the patch is enabled, since stat_extract_at_path is unsecure and complex. If it is needed, it needs to be rewritten in a clean and secure 
way using standard C++ and boost libraries

2023-11-08 15:43 UTC, kladkogex commented on libethereum/Precompiled.cpp
>          dev::u256 uValue( strValue.c_str() );
c_str() is not needed here since the constructor takes std::string

2023-11-08 15:43 UTC, kladkogex commented on libethereum/Precompiled.cpp
>      //"params.*",
Please correct stat_parse_u256_hex_or_dec() function.

The constructor of u256 boost::multiprecision::number can take both decimal and hex string and autodetect. 

Therefore, this function can be simplified to just calling constructor of u256

2023-11-08 15:43 UTC, kladkogex commented on libethereum/Precompiled.cpp
Please make sure that the precompiled call only succeeds if the correct parameter (parameter name) is provided by the caller. In all other cases the call should revert

2023-11-08 15:43 UTC, kladkogex commented on libethereum/Precompiled.cpp
> +    // remove these config field from public access for security reasons
Please remove all dead code in comments as per code guidelines.

2023-11-08 15:43 UTC, kladkogex commented on libethereum/Precompiled.cpp
> +    //    "skaleConfig.nodeInfo.wallets.ima.commonBLSPublicKey*",
Function parseHistoricFieldReuqest should parse callData into 

Json::Value object (or into nlohmann json object)

And then verify that the object contains the required fields.

It should not use log level string arithmetic

2023-11-13 14:58 UTC, dimalit approved these changes, later dismissed

2023-11-21 12:27 UTC, kladkogex approved these changes, later dismissed

2023-11-22 17:05 UTC, dimalit submitted a review, later dismissed

2023-11-22 18:22 UTC, DmytroNazarenko approved these changes

2023-11-22 18:23 UTC, dimalit approved these changes

2023-11-23 16:29 UTC, kladkogex approved these changes

2023-11-23 16:37 UTC, merged