1664 eth trace current
skalenetwork/skaled pull request #1734
Opened 2023-11-28 13:55 UTC by kladkogex

2023-12-04 13:40 UTC, olehnikolaiev commented on libweb3jsonrpc/Debug.cpp
> +    if ( m_enablePrivilegedApis ) {
shouldn't it be `!m_enablePrivelegedApis`?

2023-12-04 20:16 UTC, DmytroNazarenko requested changes

2023-12-04 20:16 UTC, DmytroNazarenko commented on README.md
> +sudo apt install nettle-dev libhiredis-dev redis-server google-perftools libgoogle-perftools-dev lcov sudo apt-get install libv8-dev
Can you please fix typo

2023-12-04 20:16 UTC, DmytroNazarenko commented on libethereum/Client.cpp
> +    Block previousBlock = blockByNumber( _blockNumber - 1 );
What if _blockNumber == 0?

2023-12-04 20:16 UTC, DmytroNazarenko commented on libethereum/Client.cpp
> +    for ( unsigned k = 0; k < transactions.size(); k++ ) {
Do we need to handle 0-gas transactions?

2023-12-04 20:16 UTC, DmytroNazarenko commented on libhistoric/AlethStandardTrace.cpp
> +        auto s = ( uint32_t ) _vm->getStackElement( 1 );
Please, use more descriptive names for b & s

2023-12-04 20:16 UTC, DmytroNazarenko commented on libhistoric/AlethStandardTrace.cpp
> +const h256& AlethStandardTrace::getTxHash() const {
Please add blank lines between functions for readability

2023-12-04 20:16 UTC, DmytroNazarenko commented on libhistoric/FunctionCallRecord.cpp
> +uint64_t FunctionCallRecord::getFunctionGasLimit() const {
Please add blank lines between functions

2023-12-11 15:32 UTC, DmytroNazarenko requested changes

2023-12-11 15:32 UTC, DmytroNazarenko commented on README.md
> +sudo apt install nettle-dev libhiredis-dev redis-server google-perftools libgoogle-perftools-dev lcov sudo apt-get install libv8-dev
Please, fix the typo

2023-12-11 15:32 UTC, DmytroNazarenko commented on libhistoric/AlethStandardTrace.cpp
> +        auto s = ( uint32_t ) _vm->getStackElement( 1 );
Please, use more descriptive names for b & s

2023-12-11 23:32 UTC, merged