Bug/1433 cleanup shared space if unsuccessful download
skalenetwork/skaled pull request #1740
Opened 2023-12-04 17:32 UTC by olehnikolaiev

fixes https://github.com/skalenetwork/skaled/issues/1433

tested manually on devnet

2023-12-04 17:37 UTC, DmytroNazarenko submitted a review, later dismissed

2023-12-04 20:11 UTC, kladkogex requested changes
Please add a step by step test description, so another person can reproduce the test

2023-12-05 10:51 UTC, dimalit approved these changes

2023-12-05 12:38 UTC, kladkogex approved these changes

2023-12-05 12:40 UTC, merged