Reload rotation timestamp on each isExitTime request
skalenetwork/skaled pull request #1757
Opened 2023-12-15 15:32 UTC by badrogger

### Problem 
The solution for https://github.com/skalenetwork/internal-support/issues/450 making skale-admin will write it to corresponding file directly instead of sending rpc call. The issue is that InstanceMonitor.cpp loads this file once during startup, which effectively says that timestamp won't be passed to skaled at all. 

### Changes
isExitTime will check the content of rotation.txt file and compare it to current block timestamp instead on relaying on m_finishTimestamp field.

### Performance 
Since rotation.txt file is only 4 bytes and reading is happening in background performance should not be affected. 
### Unit tests
Modified tests InstanceMonitorTest.cpp.

### Testing 
Tested by running rotation procedure on local network.

2023-12-18 19:50 UTC, DmytroNazarenko requested changes

2023-12-18 19:50 UTC, DmytroNazarenko commented on libethereum/InstanceMonitor.cpp
> -    return m_finishTimestamp <= _finishTimestamp;
It's better to write information about rotation into logs

2023-12-18 19:50 UTC, DmytroNazarenko commented on libethereum/InstanceMonitor.cpp
>  bool InstanceMonitor::isTimeToRotate( uint64_t _finishTimestamp ) {
Better to rename the parameter to `currentTimestamp`/`blockTimestamp` or sth like this

2023-12-27 13:24 UTC, kladkogex reviewed
Change .txt to .json

2023-12-27 13:24 UTC, kladkogex commented on libethereum/InstanceMonitor.cpp
> +    auto timestamp = rotationJson["timestamp"].get< uint64_t >();
Add try catch to handle the case of corrupt file

2023-12-27 13:26 UTC, kladkogex commented on libethereum/InstanceMonitor.cpp
> +    LOG( m_logger ) << "Set rotation time to " << _finishTimestamp;
Add try catch

2023-12-27 13:28 UTC, kladkogex commented on libethereum/InstanceMonitor.h
> +    mutable dev::Logger m_logger{ createLogger( dev::VerbosityInfo, "instance-monitor" ) };
mutable is not needed here

2023-12-28 13:07 UTC, dimalit approved these changes, later dismissed

2024-01-04 17:06 UTC, kladkogex approved these changes, later dismissed

2024-01-04 19:52 UTC, dimalit submitted a review, later dismissed

2024-01-04 20:22 UTC, DmytroNazarenko requested changes

2024-01-04 20:22 UTC, DmytroNazarenko commented on libethereum/InstanceMonitor.h
> +    mutable dev::Logger m_error_logger{ createLogger( dev::VerbosityError, "instance-monitor" ) };
Change to camelCase

2024-01-05 20:04 UTC, DmytroNazarenko approved these changes

2024-01-08 13:22 UTC, olehnikolaiev approved these changes

2024-01-09 13:16 UTC, merged