1751 trace transaction from a single user
skalenetwork/skaled pull request #1783
Opened 2024-01-15 15:50 UTC by kladkogex

WHAT WAS FIXED

Trace was not working if a block has multiple transactions (from a single entity or from multiple entities) 

There were two problems:

1) When the block was executed, receipts were not saved.   Execution of a transaction requires receipt of the previous transaction since it includes the totalgas used so far. This is important for block gas limit.

TESTS

I modified the test tracer.ts. Now the test inserts a transaction before the test transaction, so in the test the block 
includes two transactions.

As before, the test runs as part of github actions.

2024-01-19 15:54 UTC, DmytroNazarenko requested changes

2024-01-19 15:54 UTC, DmytroNazarenko commented on libethereum/Client.cpp
> +            cerr << "match !!!" << endl;
Please, remove redundant log

2024-01-19 15:54 UTC, DmytroNazarenko commented on libhistoric/AlethStandardTrace.cpp
> +void eth::AlethStandardTrace::printTrace( ExecutionResult& _er, const HistoricState& _statePre,
Please, add a blank line between methods

2024-01-19 15:54 UTC, DmytroNazarenko commented on libhistoric/AlethStandardTrace.cpp
> +
Please, use 1 blank line between methods

2024-01-19 15:54 UTC, DmytroNazarenko commented on libhistoric/ReplayTracePrinter.cpp
> +    }
Probably it is better to replace
```
if ( !topFunctionCallRecord ) {
} else {
}
```
with
```
if ( topFunctionCallRecord ) {
}
```

2024-01-22 12:54 UTC, DmytroNazarenko approved these changes

2024-01-22 15:14 UTC, olehnikolaiev approved these changes

2024-01-22 15:17 UTC, merged