Develop to 3.17.2 merge
skalenetwork/skaled pull request #1839
Opened 2024-02-29 11:52 UTC by kladkogex

Develop to 3.17.2 merge

2024-02-29 18:18 UTC, olehnikolaiev submitted a review, later dismissed

2024-02-29 19:12 UTC, dimalit approved these changes, later dismissed

2024-02-29 19:22 UTC, DmytroNazarenko requested changes

2024-02-29 19:22 UTC, DmytroNazarenko commented on VERSION
> +3.18.0
Need to be updated to 3.18.1

2024-03-01 11:32 UTC, DmytroNazarenko approved these changes

2024-03-01 11:36 UTC, olehnikolaiev approved these changes

2024-03-01 11:36 UTC, dimalit approved these changes

2024-03-01 12:01 UTC, merged