Enhancement/skaled 1583 patch architecture plus 17.2
skalenetwork/skaled pull request #1868
Opened 2024-04-10 16:01 UTC by dimalit

fixes #1583 

## Description

1. "Forks" are now activated by block timestamp, rather than number.
2. There are DEFINE_XXX_PATCH macros for defining patches.
3. Timestamps for patches are automatically read from config.
4. Existing patches use these macros.

## Tests

Tests for patches:
 - ContractStorageLimitPatch: storage_limit_reverted
 - ContractStorageZeroValuePatch: tested manually, used in test storage_limit_predeployed
 - RevertableFSPatch: FilestorageCacheSuite)
 - StorageDestructionPatch: tested manually with `JsonRpcSuite/simple_contract`
 - POWCheckPatch: powTxnGasLimit
 - PushZeroPatch: LegacyVMSuite/InstructionSuite
 - SkipInvalidTransactionsPatch: SkaleHostSuite
 - PrecompiledConfigPatch: PrecompiledTests/getConfigVariable
 - CorrectForkInPowPatch: simplePoWTransaction
 - VerifyDaSigsPatch - need to check manually!

## Performance Impact

There can be significant performance impact, as patch activations are evaluated at each block or sometimes even every transaction. This is to be tested separately

## Details about changes in code

1. A lot of functions that needed only `blockNumber` parameter now need also `committedBlockTimestamp`.
2. Removed 'Frontier' fork (it was never used), as well as 'SkaleNNNForkBlock`s for same reson.
3. `EVMSchedule` can now be constructed from several patches, and not only taken from pre-defined list as before (`ChainOperationParams::evmSchedule`)
4. Some functionality moved from `SealEngine` to `ChainOperationParams`, and `SealEngine` is now unneeded in some places, where `ChainOperationParams` suffice - for simplification of architecture. Also it's planned to cut out SealEngine completely.
5. `PushZeroPatch` uses boolean field in `EVMSchedule`, and generates new EVMSchedule similar to 'fork blocks'
6. In `libethereum/SchainPatch.h` there are new macros for creation of patches.
7. Almost all old patches now use these macros (see SchainPatch.h)
8. Latest block timestamp is updated every block for all patches at once - in `SchainPatch` class.

2024-04-11 12:56 UTC, kladkogex submitted a review, later dismissed

2024-04-15 12:23 UTC, olehnikolaiev approved these changes, later dismissed

2024-04-15 15:04 UTC, DmytroNazarenko requested changes

2024-04-15 15:04 UTC, DmytroNazarenko commented on libethereum/ClientBase.cpp
> +        _pendingBlock.previousInfo().timestamp(), 0, _gas );
Mb `_pendingBlock.previousInfo().timestamp()` -> `_latestBlock.info().timestamp()` would be better?

2024-04-15 15:04 UTC, DmytroNazarenko commented on libethereum/ClientBase.cpp
> +                                 Transaction::baseGasRequired( !_dest, &_data, EVMSchedule() );
if/else would be more readable here

2024-04-15 15:04 UTC, DmytroNazarenko commented on libethereum/SkaleHost.cpp
> +                            .timestamp(),
This call could be retrieved and executed before loop

2024-04-15 15:04 UTC, DmytroNazarenko commented on libethereum/SkaleHost.cpp
> +                    m_client.blockInfo( LatestBlock ).timestamp(), m_client.number(), true );
`m_client.blockInfo( LatestBlock ).timestamp()` can be executed before loop

2024-04-16 14:32 UTC, dimalit commented on libethereum/ClientBase.cpp
> +        _pendingBlock.previousInfo().timestamp(), 0, _gas );
same

2024-04-16 14:34 UTC, dimalit commented on libethereum/ClientBase.cpp
> +                                 Transaction::baseGasRequired( !_dest, &_data, EVMSchedule() );
:+1:

2024-04-16 14:36 UTC, dimalit commented on libethereum/SkaleHost.cpp
> +                            .timestamp(),
:ok_hand:

2024-04-16 14:50 UTC, dimalit commented on libethereum/SkaleHost.cpp
> +                    m_client.blockInfo( LatestBlock ).timestamp(), m_client.number(), true );
:+1:

2024-04-16 18:08 UTC, kladkogex reviewed
Please remove exclamation marks and dead code

2024-04-17 12:23 UTC, kladkogex approved these changes

2024-04-17 14:37 UTC, DmytroNazarenko approved these changes

2024-04-17 14:45 UTC, merged