Adding data field for reverted calls and estimateGas
skalenetwork/skaled pull request #1960
Opened 2024-08-14 19:08 UTC by DmytroNazarenko

## Description

This PR adds support of "data" field for reverted `eth_call` and `eth_estimateGas`. Example of the response:
```
{
   "error":{
      "code":-32004,
      "data":"0x82b42900",
      "message":"EVM revert instruction without description message"
   },
   "id":2327090862,
   "jsonrpc":"2.0"
}
```

## Tests

### Unit tests

Added 2 unit tests: `JsonRpcSuite/estimate_gas_with_error` and `JsonRpcSuite/call_with_error`

### Additional tests

Here is the testing procedure on the local machine:

1. Deploying contract 
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract BasicCustomErrorContract {

    // Define custom errors
    error InsufficientBalance();
    error Unauthorized();

    address public owner;

    // Function only callable by the owner
    function ownerOnlyFunction() external {
        revert Unauthorized();
    }

    function requireCall() external {
        require(1 == 0, "Require");
    }

    function revertCall() external {
        revert("Something bad happened");
    }

    function assertCall() external {
        assert(1 == 0);
    }
}
```
2. Sending eth_calls:
```
curl SKALED_ENDPOINT -X POST -H "Content-Type: application/json"   --data '{"id":2327090862,"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0x82b42900","from":"0xa68F946090c600eDa6f139783077EE802Afeb990","to":"0x62815b8b66a91fef35d7950f83c04da6a64508c2","value":"0x0"},"latest"]}'
curl SKALED_ENDPOINT -X POST -H "Content-Type: application/json"   --data '{"id":2327090862,"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0xf38fb65b","from":"0xa68F946090c600eDa6f139783077EE802Afeb990","to":"0x62815b8b66a91fef35d7950f83c04da6a64508c2","value":"0x0"},"latest"]}'
curl SKALED_ENDPOINT -X POST -H "Content-Type: application/json"   --data '{"id":2327090862,"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0x068d492b","from":"0xa68F946090c600eDa6f139783077EE802Afeb990","to":"0x62815b8b66a91fef35d7950f83c04da6a64508c2","value":"0x0"},"latest"]}'
curl SKALED_ENDPOINT -X POST -H "Content-Type: application/json"   --data '{"id":2327090862,"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0x4bc55aed","from":"0xa68F946090c600eDa6f139783077EE802Afeb990","to":"0x62815b8b66a91fef35d7950f83c04da6a64508c2","value":"0x0"},"latest"]}'
```
3. Receiving responses:
```
{"error":{"code":-32004,"data":"0x82b42900","message":"EVM revert instruction without description message"},"id":2327090862,"jsonrpc":"2.0"}
{"error":{"code":-32004,"data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000016536f6d657468696e67206261642068617070656e656400000000000000000000","message":"Something bad happened"},"id":2327090862,"jsonrpc":"2.0"}
{"error":{"code":-32004,"data":"0x4e487b710000000000000000000000000000000000000000000000000000000000000001","message":"EVM revert instruction without description message"},"id":2327090862,"jsonrpc":"2.0"}
{"error":{"code":-32004,"data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000075265717569726500000000000000000000000000000000000000000000000000","message":"Require"},"id":2327090862,"jsonrpc":"2.0"}

```
4. Repeating p.3-4 for eth_estimateGas

## Performance Impact

All changes are inside JSON RPC API modules, so performance is not affected

2024-08-15 01:16 UTC, kladkogex requested changes
1 We need to find the corresponding code in geth to make sure we are doing exactly doing for this field

2. Also we need to understand how does this new field affect tracing.  Where does it show in traces? To do this, one needs to do geth trace and compare

Our strategy needs to be 100% compatible with geth

2024-08-24 12:20 UTC, kladkogex approved these changes

2024-08-27 12:53 UTC, olehnikolaiev approved these changes

2024-08-27 14:24 UTC, dimalit approved these changes

2024-08-27 14:26 UTC, merged