IS 1074 fix externalGas calculation
skalenetwork/skaled pull request #1999
Opened 2024-09-19 15:58 UTC by olehnikolaiev

fixes https://github.com/skalenetwork/internal-support/issues/1074
fix `externalGas` calculation 

added unit tests that recalculates `externalGas` for a transaction from the transaction queue

no performance impact

2024-09-20 13:24 UTC, dimalit requested changes
see comment

2024-09-20 13:24 UTC, dimalit commented on libethereum/Transaction.cpp
> +        if ( m_externalGasIsChecked && hasExternalGas() )
Why not just:
```
m_externalGasIsChecked = false;
m_externalGas.reset()'
```
without `if`?

2024-09-24 17:02 UTC, kladkogex submitted a review, later dismissed

2024-09-25 17:54 UTC, DmytroNazarenko approved these changes

2024-09-25 19:06 UTC, dimalit approved these changes

2024-09-25 19:24 UTC, kladkogex approved these changes

2024-09-25 20:15 UTC, merged