SKALE-3308 handling exit in skaled with iunique exit codes everywhere
skalenetwork/skaled pull request #355
Opened 2020-09-25 12:28 UTC by sergiy-skalelabs

- added unique exit codes into dev::ExitHandler everywhere in skaled

2020-09-25 13:22 UTC, DmytroNazarenko requested changes

2020-09-25 13:22 UTC, DmytroNazarenko commented on libdevcore/Common.h
> +        ec_rotation_complete = 197,            // exit requested after rotation complete
Return code after completed node rotation should be 0, to avoid restarting of skaled container by docker

2020-09-26 04:38 UTC, DmytroNazarenko approved these changes

2020-09-29 12:54 UTC, dimalit approved these changes

2020-09-29 13:34 UTC, merged