SKALE-3962 cleanup before starting from snapshot
skalenetwork/skaled pull request #509
Opened 2021-03-05 09:15 UTC by olehnikolaiev

2021-03-05 13:16 UTC, dimalit reviewed
I think with these changes we don't need check for same snapshot presence anymore. BUT need to carefully check case latest snpshot == 0. I will take a look.

2021-03-05 14:20 UTC, dimalit reviewed
UPD If we crashed, and it's just docker restarting us - need to check if can just safely run without any download!

2021-03-05 14:28 UTC, dimalit requested changes
I blocked PR until we implement mentioned above updates.

2021-03-11 17:53 UTC, sergiy-skalelabs approved these changes, later dismissed

2021-03-12 10:47 UTC, sergiy-skalelabs submitted a review, later dismissed

2021-03-12 16:03 UTC, merged