Enhancement/skale 4087 snapshot improvements
skalenetwork/skaled pull request #572
Opened 2021-04-20 13:32 UTC by olehnikolaiev

add snapshot components' hashes to logs
rework adding last price to snapshot hash

2021-04-20 13:42 UTC, sergiy-skalelabs approved these changes, later dismissed

2021-04-20 13:51 UTC, sergiy-skalelabs submitted a review, later dismissed

2021-04-20 16:12 UTC, kladkogex submitted a review, later dismissed

2021-04-23 09:26 UTC, sergiy-skalelabs submitted a review, later dismissed

2021-04-23 10:29 UTC, kladkogex submitted a review, later dismissed

2021-04-23 10:33 UTC, dimalit requested changes
Let me look

2021-04-26 14:33 UTC, dimalit approved these changes

2021-04-26 14:44 UTC, merged