Enhancement/IMA-2-Main-Net connectivity improvements in beta
skalenetwork/skaled pull request #764
Opened 2021-08-21 19:57 UTC by sergiy-skalelabs

- IMA-2-Main-Net connectivity improvements

2021-08-21 22:25 UTC, cstrangedk requested changes

2021-08-21 22:25 UTC, cstrangedk commented on libskutils/src/rest_call.cpp
> +            throw std::runtime_error( "sz_cli: could not client key read file \"" +
please fix error message

2021-08-21 22:25 UTC, cstrangedk commented on libskutils/src/rest_call.cpp
> +    std::chrono::milliseconds wait_step, size_t cntSteps, bool isReturnErrorResponce ) {
typo, please fix all instances. isReturnErrorResponce -> isReturnErrorResponse.

2021-08-21 22:36 UTC, sergiy-skalelabs commented on libskutils/src/rest_call.cpp
> +            throw std::runtime_error( "sz_cli: could not client key read file \"" +
fixed

2021-08-21 22:38 UTC, sergiy-skalelabs commented on libskutils/src/rest_call.cpp
> +    std::chrono::milliseconds wait_step, size_t cntSteps, bool isReturnErrorResponce ) {
fixed, thanx

2021-08-25 09:06 UTC, kladkogex approved these changes

2021-08-25 09:47 UTC, merged