Add precompile info for 3.8
skalenetwork/skaled pull request #854
Opened 2021-10-25 23:18 UTC by cstrangedk

2021-10-27 12:50 UTC, DmytroNazarenko requested changes

2021-10-27 12:50 UTC, DmytroNazarenko commented on docs/modules/ROOT/pages/random-number-generator.adoc
> +Running getRandom() from Remix several times will return the following example output:
I think need to append with `output for each of the new blocks:`

2021-10-27 12:50 UTC, DmytroNazarenko commented on docs/modules/ROOT/pages/precompiles.adoc
> +Each SKALE Chain comes with a set of precompiled contracts in addition to the precompiles included with Ethereum (i.e. `ecrecover`, `sha256`, `modexp`, ...).
Need to add some info about `restrictAccess` option - to protect precompiled from external calls. Only specific address could call marked precopmileds. This option is used for filestorage precompileds (0x0B, 0x0C, 0x0E,0x0F, 0x10). Other are free to call. Example:
```
                "startingBlock": "0x0",
                "restrictAccess": [
                    "0xD3002000000000000000000000000000000000D3"
                ]
```

2021-10-27 17:01 UTC, cstrangedk commented on docs/modules/ROOT/pages/precompiles.adoc
> +Each SKALE Chain comes with a set of precompiled contracts in addition to the precompiles included with Ethereum (i.e. `ecrecover`, `sha256`, `modexp`, ...).
added new column for clarification

2022-02-17 09:21 UTC, DmytroNazarenko approved these changes

2022-02-18 17:19 UTC, merged